### ISSUE TITLE
Addon Exception - unicode file/path issue

### ISSUE THREAD

**Issue by mgonzales71** [cibboy/script.profilecleaner#2]
Hi cibboy,

Found your addon today and decided to give it a test.

Hit an exception with the addon cleanup portion of the script, looks like it is due to special characters in unicode file / path names.

Error:

```
22:03:52 T:6372  NOTICE: [Profile Cleaner] - Addon cleanup started at 2016-05-30 22:03:30
22:03:56 T:6372   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: (2, 'The system cannot find the file specified', 'C:\\Users\\Mario\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skin.helper.service\\artworkcache\\Cherno\xb4bil, la noche del fin del mundo-2008.xml')
                                            Traceback (most recent call last):
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.profilecleaner\script.py", line 981, in <module>
                                                elif selection == 3: remain = True; Cleaner().PerformCleanup(8)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.profilecleaner\script.py", line 963, in PerformCleanup
                                                self.AddonCleanup()
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.profilecleaner\script.py", line 775, in AddonCleanup
                                                self.totalAddonSize = self.totalAddonSize + self.GetFolderSize(os.path.join(addonData, item))
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.profilecleaner\script.py", line 752, in GetFolderSize
                                                total_size += os.path.getsize(fp)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\genericpath.py", line 49, in getsize
                                                return os.stat(filename).st_size
                                            WindowsError: (2, 'The system cannot find the file specified', 'C:\\Users\\Mario\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skin.helper.service\\artworkcache\\Cherno\xb4bil, la noche del fin del mundo-2008.xml')
                                            -->End of Python script error report<--
```

the path and file name:

**C:\Users\Mario\AppData\Roaming\Kodi\userdata\addon_data\script.skin.helper.service\artworkcache\Chernóbil, la noche del fin del mundo-2008.xml**

If I delete the file in question the script eventually hit another file / path with a special character in it and again throws an exception:

```
22:15:52 T:6988  NOTICE: [Profile Cleaner] - Addon cleanup started at 2016-05-30 22:15:30
22:15:56 T:6988   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: (2, 'The system cannot find the file specified', 'C:\\Users\\Mario\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skin.helper.service\\artworkcache\\Csernobil O\xa8ro\xa8kse\xb4ge a Zo\xb4na-2011.xml')
                                            Traceback (most recent call last):
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.profilecleaner\script.py", line 981, in <module>
                                                elif selection == 3: remain = True; Cleaner().PerformCleanup(8)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.profilecleaner\script.py", line 963, in PerformCleanup
                                                self.AddonCleanup()
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.profilecleaner\script.py", line 775, in AddonCleanup
                                                self.totalAddonSize = self.totalAddonSize + self.GetFolderSize(os.path.join(addonData, item))
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.profilecleaner\script.py", line 752, in GetFolderSize
                                                total_size += os.path.getsize(fp)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\genericpath.py", line 49, in getsize
                                                return os.stat(filename).st_size
                                            WindowsError: (2, 'The system cannot find the file specified', 'C:\\Users\\Mario\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skin.helper.service\\artworkcache\\Csernobil O\xa8ro\xa8kse\xb4ge a Zo\xb4na-2011.xml')
                                            -->End of Python script error report<--
```

This time for:

**C:\Users\Mario\AppData\Roaming\Kodi\userdata\addon_data\script.skin.helper.service\artworkcache\Csernobil Öröksége a Zóna-2011.xml**

a pretty picture :smile:

![2016-05-30_22-08-44](https://cloud.githubusercontent.com/assets/6510026/15663989/088c5fa2-26b5-11e6-81eb-d730799c2822.png)

Thanks for coding this - I had considered trying the texture cache maintenance utillity but don't want to mess with scripts especially when I have non-computer folks that I don't want to hold a special class to teach them how to use it.

Have a great week!

Mario

**Comment by cibboy** [comment]
Hi Mario!

I'm unable to replicate your problem: I tried to create a file with the same name and run the script, but it doesn't crash. Could you please try and add the following string as the first line of script.py and try again?

`# -*- coding: utf-8 -*-`

Copy it exactly as it is, so that the file should look like this at the beginning:

```
# -*- coding: utf-8 -*-
import xbmc, xbmcgui
import os, sys, urllib, datetime, time, shutil, re
...
```

Let me know how it works.
Thanks.

Gabriele

**Comment by mgonzales71** [comment]
Still get errors when a "special" character in a filename / path is hit.

I if delete the file the script will work (unless another file with a special character is hit)

as a test I removed all but the settings.xml for the helper script and your script worked fine.

if you want to look at the script or as Marcel (the author of the script) he and his code are here:

https://github.com/marcelveldt/script.skin.helper.service

Thanks for your reply and let me know if I can help or test any further for you!

Mario

![2016-06-01_17-44-24](https://cloud.githubusercontent.com/assets/6510026/15730341/97b7d370-2820-11e6-8b1a-a0c0444ae6b2.png)

**Comment by mgonzales71** [comment]
oh and btw - I am running Kodi 16.1 on Windows 10 x64 pro

**Comment by cibboy** [comment]
I have your exact same configuration. Looking a bit deeper into Windows configuration I have the following locale configuration (region settings from the traditional control panel):
- Format: Italian (Italy)
- Administrative -> Language for non-Unicode programs: English (United States)

Furthermore, the display language is English (United States)
If you have the chance, try tinkering with those settings and let's see what happens.

In the meantime, as a quick test, you could add the following code at line 748:
`os.path.supports_unicode_filenames`
The code around that location should then look like this:

```
def GetFolderSize(self, start_path = '.'):
    log("Support for unicode: " + os.path.supports_unicode_filenames)
    total_size = 0
```

Once the script runs you should be able to see in the log (several times) if your configuration supports unicode filenames. I expect it to, but you never know :)

Thanks for the patience.

**Comment by mgonzales71** [comment]
info at this link may be helpful:

http://stackoverflow.com/questions/10288821/encoding-unicode-path-with-filesystem-encoding-breaks-it

Also I tried this code to find out what is up with the encoding of the filesystem and if the os.path.supports_unicode_filenames was true or false....

```
    def GetFolderSize(self, start_path = '.'):
        os.path.supports_unicode_filenames
        log("os.path.supports_unicode_filenames : " + str( os.path.supports_unicode_filenames ) )
        log("file system encoding : " + sys.getfilesystemencoding() )
        total_size = 0
        for dirpath, dirnames, filenames in os.walk(start_path):
            for f in filenames:
                fp = os.path.join(dirpath, f)
                total_size += os.path.getsize(fp)
        return total_size

```

still hit the error but have more info:

```
20:41:45 T:9828  NOTICE: [Profile Cleaner] - Addon cleanup started at 2016-06-02 20:41:02
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:45 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:45 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:46 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:46 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:46 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:46 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828  NOTICE: [Profile Cleaner] - os.path.supports_unicode_filenames : True
20:41:49 T:9828  NOTICE: [Profile Cleaner] - file system encoding : mbcs
20:41:49 T:9828   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: (2, 'The system cannot find the file specified', 'C:\\Users\\Mario\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skin.helper.service\\musicartcache\\Beyonce\xb4-Run the World Girls - Single.xml')
                                            Traceback (most recent call last):
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.profilecleaner\script.py", line 985, in <module>
                                                elif selection == 3: remain = True; Cleaner().PerformCleanup(8)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.profilecleaner\script.py", line 967, in PerformCleanup
                                                self.AddonCleanup()
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.profilecleaner\script.py", line 779, in AddonCleanup
                                                self.totalAddonSize = self.totalAddonSize + self.GetFolderSize(os.path.join(addonData, item))
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.profilecleaner\script.py", line 756, in GetFolderSize
                                                total_size += os.path.getsize(fp)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\genericpath.py", line 49, in getsize
                                                return os.stat(filename).st_size
                                            WindowsError: (2, 'The system cannot find the file specified', 'C:\\Users\\Mario\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skin.helper.service\\musicartcache\\Beyonce\xb4-Run the World Girls - Single.xml')
                                            -->End of Python script error report<--

```

think this google search may be helpful - https://goo.gl/U69dxQ

I wish I knew Python beyond the very basics so I could be more helpful.

Thanks again and let me know if I can test, etc for you further :smile:

Mario

**Comment by mgonzales71** [comment]
PS.... just in case it's helpful..

I found this: http://stackoverflow.com/questions/10288821/encoding-unicode-path-with-filesystem-encoding-breaks-it

that lead to this: http://stackoverflow.com/questions/1910275/unicode-filenames-on-windows-with-python-subprocess-popen

Hmm - a known bug in python 2.x ?

I know I am probably grasping at straws hehe

**Comment by cibboy** [comment]
I don't know Python well either, unfortunately :)
I doubt, though, that it's a bug in Python 2.x (even though reading those posts make me wish for Python 3.x in Kodi).
Since we're all grasping at straws here, could you please try and replace line 751 with:
`fp = os.path.join(dirpath, f).encode('utf-8')`
When I try it I get an exception because my string is already encoded in utf-8 I guess, but maybe yours isn't, so it could solve your issue.

Let me know.

**Comment by mgonzales71** [comment]
I actually wanted to follow up - I used a windows app to take my entire music library and fingerprint it and correct all the tags, file names, artwork, etc - there was an option to remove/rename special characters and since I did that I haven't had any more issues - obviously the change above worked too - but I don't know if what I did or that code change is the real fix.

later today I will re-create a file that was tripping things up before and see if I get an error.

Thanks again! :)

mario

**Comment by Grossdm** [comment]
@cibboy, I am also quite a novice with Python - but I have messed around with the code in several addons.
Your attempt to encode as utf-8 which fails when the string is already unicode might work with this.

```
try:
    fp = os.path.join(dirpath, f).encode('utf-8')
except:
    fp = os.path.join(dirpath, f)
```
